default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  sslmode: require

development:
  <<: *default
  database: orderbook-development

test:
  <<: *default
  database: orderbook-test

production:
  <<: *default
  database: orderbook-production
  username: orderbook-user
  password: <%= ENV['ORDERBOOK_DATABASE_PASSWORD'] %>